[tools]
node = "18"

[env]
PUBLIC_FIREBASE_API_KEY='AIzaSyDVeb6azdjnk1Ec3fgfWegvwyAAEETQPHs' # pragma: allowlist secret
PUBLIC_FIREBASE_AUTH_DOMAIN='ltcat-340f7.firebaseapp.com'
PUBLIC_FIREBASE_PROJECT_ID='ltcat-340f7'
PUBLIC_FIREBASE_STORAGE_BUCKET='ltcat-340f7.appspot.com'
PUBLIC_FIREBASE_MESSAGING_SENDER_ID='733830252896'
PUBLIC_FIREBASE_APP_ID='1:733830252896:web:1e75f66f8f7f3f036cf605'
PUBLIC_FIREBASE_MEASUREMENT_ID='G-6PC24D198C'
